# version: "3.8"  # Update the version to a more recent one (optional)

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: myuser  # Set your username
      RABBITMQ_DEFAULT_PASS: mypassword  # Set your password  

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - rabbitmq  # Ensure RabbitMQ is started before this service
    volumes:
      - .:/app
      - /app/products/node_modules
    env_file:
      - ./products/.env

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - rabbitmq  # Ensure RabbitMQ is started before this service
    volumes:
      - .:/app
      - /app/shopping/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - rabbitmq  # Ensure RabbitMQ is started before this service
    volumes:
      - .:/app/
      - /app/customer/node_modules
    env_file:
      - ./customer/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - shopping
      - customer
    ports:
      - 80:80